GET 10.1.31.225/rss/api/auths/login?username=20220463&password=20220463  HTTP/1.1
###

###
GET http://10.1.31.190/rss/api/auths/login?username=20220463&password=e49cd60aed73079a31f0af90f251244e HTTP/1.1
Content-Type: application/json; charset=UTF-8 

###
POST  http://10.1.31.190/rss/api/ftp/search  HTTP/1.1
Content-Type: application/json; charset=UTF-8 
Authorization: Bearer {"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhY2Nlc3NUb2tlbiIsImV4cCI6MTY3NjQ1NDk5NCwiaWF0IjoxNjc2NDQwNTk0LCJ1c2VySWQiOjEwMDAxLCJ1c2VyTmFtZSI6IjIwMjIwNDYzIiwicGVybWlzc2lvbiI6IiJ9.wJqHABn7NA1YNA_X37pwDJTTq7O9KQhPvLgQZFwU9Tw"}

{
    "data":{
            "fabNames": ["Line1"],
            "machineNames": ["MPA_208"],
            "categoryCodes": ["001"],
            "categoryNames": ["RUNNING_STATUS"],
            "startDate": "20221001144108",
            "endDate": "20230215144113",
            "folder": false, 
            "depth": 999
    }
}
###
POST http://10.1.31.190/rss/api/ftp/search  HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhY2Nlc3NUb2tlbiIsImV4cCI6MTY3Njk2MzY3MSwiaWF0IjoxNjc2OTQ5MjcxLCJ1c2VySWQiOjEwMDAxLCJ1c2VyTmFtZSI6IjIwMjIwNDYzIiwicGVybWlzc2lvbiI6IiJ9.W2cEBJcLwUNt6xx5o-z6o0VCtmQXONlGkNqUcGpDNZM

{
    "data": {
        "fabNames":["line1"],
        "machineNames":["MPA_2"],
        "categoryCodes":["001"],
        "categoryNames":["RUNNING_STATUS"],
        "startDate":"20220801000000",
        "endDate":"20230119235959",
        "folder":false,
        "depth":999
    }
}

###
GET http://10.1.31.190/rss/api/ftp/search/SFTP-20230221121443210-5036 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhY2Nlc3NUb2tlbiIsImV4cCI6MTY3Njk2MzY3MSwiaWF0IjoxNjc2OTQ5MjcxLCJ1c2VySWQiOjEwMDAxLCJ1c2VyTmFtZSI6IjIwMjIwNDYzIiwicGVybWlzc2lvbiI6IiJ9.W2cEBJcLwUNt6xx5o-z6o0VCtmQXONlGkNqUcGpDNZM
{
    "searchId": "SFTP-20230221121635901-5039"
}

