[
    {
        "machineName": "192OTS",
        "host": "10.1.31.192",
        "ots": null,
        "line": null,
        "ftpUser": null,
        "ftpPassword": null,
        "vftpUser": null,
        "vftpPassword": null,
        "serialNumber": null,
        "toolType": null,
        "port": 80,
        "ftpConnected": true,
        "equipmentId": null,
        "vftpConnected": true
    },
    {
        "machineName": "MPA_2",
        "host": "10.1.31.216",
        "ots": "192OTS",
        "line": "Line1",
        "ftpUser": "ckbs",
        "ftpPassword": "ckbs",
        "vftpUser": "ckbs",
        "vftpPassword": "ckbs",
        "serialNumber": "serial",
        "toolType": "tooltyp",
        "port": 0,
        "ftpConnected": false,
        "equipmentId": "MPAUltmIKZEBXNcA",
        "vftpConnected": false
    },
    {
        "machineName": "MPA_222",
        "host": "10.1.31.216",
        "ots": "192OTS",
        "line": "Line2",
        "ftpUser": "ckbs",
        "ftpPassword": "ckbs",
        "vftpUser": "ckbs",
        "vftpPassword": "ckbs",
        "serialNumber": "serial",
        "toolType": "tooltyp",
        "port": 0,
        "ftpConnected": false,
        "equipmentId": "MPAaZIUidekNkJBg",
        "vftpConnected": false
    },
    {
        "machineName": "MPA_208",
        "host": "10.1.31.208",
        "ots": "192OTS",
        "line": "Line1",
        "ftpUser": "ckbs",
        "ftpPassword": "ckbs",
        "vftpUser": "ckbs",
        "vftpPassword": "ckbs",
        "serialNumber": "qq",
        "toolType": "tt",
        "port": 0,
        "ftpConnected": true,
        "equipmentId": "MPAngygwGBdqgYgX",
        "vftpConnected": true
    },
    {
        "machineName": "MPA_2081",
        "host": "10.1.31.208",
        "ots": "192OTS",
        "line": "Line3",
        "ftpUser": "ckbs",
        "ftpPassword": "ckbs",
        "vftpUser": "ckbs",
        "vftpPassword": "ckbs",
        "serialNumber": "fwe",
        "toolType": "f",
        "port": 0,
        "ftpConnected": true,
        "equipmentId": "MPAeSyti6RyLv1gW",
        "vftpConnected": true
    },
    {
        "machineName": "MPA_2082",
        "host": "10.1.31.208",
        "ots": "192OTS",
        "line": "Line3",
        "ftpUser": "ckbs",
        "ftpPassword": "ckbs",
        "vftpUser": "ckbs",
        "vftpPassword": "ckbs",
        "serialNumber": "asg",
        "toolType": "asa",
        "port": 0,
        "ftpConnected": true,
        "equipmentId": "MPAiGuSOtHiRJdQt",
        "vftpConnected": true
    },
    {
        "machineName": "MPA_2083",
        "host": "10.1.31.208",
        "ots": "192OTS",
        "line": "Line3",
        "ftpUser": "ckbs",
        "ftpPassword": "ckbs",
        "vftpUser": "ckbs",
        "vftpPassword": "ckbs",
        "serialNumber": "jio",
        "toolType": "sdf",
        "port": 0,
        "ftpConnected": true,
        "equipmentId": "MPA0qc1xm1O4jlOT",
        "vftpConnected": true
    },
    {
        "machineName": "MPA_2084",
        "host": "10.1.31.208",
        "ots": "192OTS",
        "line": "Line3",
        "ftpUser": "ckbs",
        "ftpPassword": "ckbs",
        "vftpUser": "ckbs",
        "vftpPassword": "ckbs",
        "serialNumber": "gg",
        "toolType": "ff",
        "port": 0,
        "ftpConnected": true,
        "equipmentId": "MPA757DpdKkj5aNc",
        "vftpConnected": true
    },
    {
        "machineName": "MPA_2_test",
        "host": "10.1.31.216",
        "ots": "192OTS",
        "line": "Line1",
        "ftpUser": "ckbs",
        "ftpPassword": "ckbs",
        "vftpUser": "ckbs",
        "vftpPassword": "ckbs",
        "serialNumber": "serial1",
        "toolType": "tooltyp",
        "port": 0,
        "ftpConnected": false,
        "equipmentId": "MPACQpxsBaR4vHbl",
        "vftpConnected": false
    },
    {
        "machineName": "227MPA_2",
        "host": "10.1.31.216",
        "ots": "192OTS",
        "line": "Line1",
        "ftpUser": "ckbs",
        "ftpPassword": "ckbs",
        "vftpUser": "ckbs",
        "vftpPassword": "ckbs",
        "serialNumber": "serial",
        "toolType": "tooltype",
        "port": 0,
        "ftpConnected": false,
        "equipmentId": "MPAeHc4D6dtqXHdV",
        "vftpConnected": false
    },
    {
        "machineName": "E813_E033",
        "host": "10.1.31.208",
        "ots": "192OTS",
        "line": "CR",
        "ftpUser": "ckbs",
        "ftpPassword": "ckbs",
        "vftpUser": "ckbs",
        "vftpPassword": "ckbs",
        "serialNumber": "s12345",
        "toolType": "cr",
        "port": 0,
        "ftpConnected": true,
        "equipmentId": "MPAtAju8JjOstwar",
        "vftpConnected": true
    }
]